# generated by datamodel-codegen:
#   filename:  csm_api-swagger.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

import cherwell_pydantic_api.types as ct
from cherwell_pydantic_api.generated_api_utils import ApiBaseModel, HttpStatusCode


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetStagesResponseStages(ApiBaseModel):
    id: Optional[str] = None
    isFinal: Optional[bool] = None
    name: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetStatusesResponseStatuses(ApiBaseModel):
    id: Optional[str] = None
    isInitial: Optional[bool] = None
    name: Optional[str] = None
    stageId: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetTransitionsResponseTransition(ApiBaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    fromStatusId: Optional[str] = None
    toStatusId: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetRecordStatusResponse(ApiBaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetTransitionOptionsResponseTransition(ApiBaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    isAvailable: Optional[bool] = None
    criteria: Optional[List[str]] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class TransitionRecordRequest(ApiBaseModel):
    transitionOptionId: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetStagesResponse(ApiBaseModel):
    stages: Optional[List[GetStagesResponseStages]] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetStatusesResponse(ApiBaseModel):
    statuses: Optional[List[GetStatusesResponseStatuses]] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetTransitionsResponse(ApiBaseModel):
    transitions: Optional[List[GetTransitionsResponseTransition]] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class GetTransitionOptionsResponse(ApiBaseModel):
    transitions: Optional[List[GetTransitionOptionsResponseTransition]] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None
