# generated by datamodel-codegen:
#   filename:  csm_api-swagger.json

from __future__ import annotations

from enum import Enum
from typing import Optional

import cherwell_pydantic_api.types as ct
from cherwell_pydantic_api.generated_api_utils import ApiBaseModel


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class AddItemToQueueRequest(ApiBaseModel):
    busObId: Optional[ct.BusObID] = None
    busObRecId: Optional[ct.BusObRecID] = None
    queueStandInKey: Optional[str] = None


import cherwell_pydantic_api.types as ct
from cherwell_pydantic_api.generated_api_utils import HttpStatusCode


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class AddItemToQueueResponse(ApiBaseModel):
    historyRecId: Optional[str] = None
    historyText: Optional[str] = None
    historyTypeId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class CheckInQueueItemRequest(ApiBaseModel):
    busObId: Optional[ct.BusObID] = None
    busObRecId: Optional[ct.BusObRecID] = None
    historyNotes: Optional[str] = None
    queueStandInKey: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class CheckInQueueItemResponse(ApiBaseModel):
    historyRecId: Optional[str] = None
    historyText: Optional[str] = None
    historyTypeId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class CheckOutQueueItemRequest(ApiBaseModel):
    busObId: Optional[ct.BusObID] = None
    busObRecId: Optional[ct.BusObRecID] = None
    historyNotes: Optional[str] = None
    queueStandInKey: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class CheckOutQueueItemResponse(ApiBaseModel):
    historyRecId: Optional[str] = None
    historyText: Optional[str] = None
    historyTypeId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class RemoveItemFromQueueRequest(ApiBaseModel):
    busObId: Optional[ct.BusObID] = None
    busObRecId: Optional[ct.BusObRecID] = None
    historyNotes: Optional[str] = None
    queueStandInKey: Optional[str] = None


import cherwell_pydantic_api.types as ct


ct  # type: ignore
from enum import Enum


Enum  # type: ignore


class RemoveItemFromQueueResponse(ApiBaseModel):
    historyRecId: Optional[str] = None
    historyText: Optional[str] = None
    historyTypeId: Optional[str] = None
    errorCode: Optional[str] = None
    errorMessage: Optional[str] = None
    hasError: Optional[bool] = None
    httpStatusCode: Optional[HttpStatusCode] = None
