# Generated by codegen.py
# pyright: reportUnusedImport=false, reportMissingTypeArgument=false

from __future__ import annotations

from typing import Any

from pydantic import RootModel

from cherwell_pydantic_api.generated_api_utils import ApiBaseModel


class CherwellModel(RootModel):
    root: Any


from enum import Enum

import cherwell_pydantic_api.types as ct
from cherwell_pydantic_api.types import CherwellObjectID
