# Generated by codegen.py
# pyright: reportUnusedImport=false, reportMissingTypeArgument=false

from __future__ import annotations

from enum import Enum
from typing import Optional

import cherwell_pydantic_api.types as ct
from cherwell_pydantic_api.generated_api_utils import ApiBaseModel

from .. import CherwellObjectID


class CherwellNameValuePair(ApiBaseModel):
    name: Optional[str] = None
    valueObject: Optional[CherwellObjectID] = None
    valueString: Optional[str] = None
    category: Optional[str] = None
    description: Optional[str] = None
    displayShowsValue: Optional[bool] = None
    specialUseFlag: Optional[bool] = None
    displayString: Optional[str] = None
